# Generated by Django 3.2 on 2021-04-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=50, unique=True, verbose_name='Category')),
                ('priority', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Project title')),
                ('description', models.TextField(verbose_name='Description')),
                ('github_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Github link of the projects')),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='The url of the launched projects')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='projects/video')),
                ('tags', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tags for the projects')),
                ('published', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.categories')),
            ],
            options={
                'verbose_name': 'Project info',
                'verbose_name_plural': 'Projects Info',
                'ordering': ('cate', 'priority'),
            },
        ),
    ]
