# Generated by Django 3.2 on 2021-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.CharField(default='', max_length=255, verbose_name='Tags for the projects'),
        ),
    ]
