# Generated by Django 3.2 on 2021-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Certification name')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageFooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='home_page_and_footer_info', max_length=50, verbose_name='Name')),
                ('content', models.TextField(help_text='The content display on the home page', verbose_name='Content')),
                ('footer', models.TextField(default='', verbose_name='Footer Content')),
            ],
        ),
    ]
